
---
spring:
  batch:
     jdbc:
       initialize-schema: never
     job:
       enabled: false
  config:
    import:
      - optional:classpath:application-secret.yml
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
        highlight_sql : true
  lifecycle:
    timeout-per-shutdown-phase: 30s

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.client.DefaultRestClient: OFF
#    org.springframework.messaging.simp: DEBUG
#    org.springframework.messaging.handler: DEBUG
#    org.springframework.messaging: DEBUG
#    org.springframework.web.socket: DEBUG

