name: Deploy to EC2 with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/saboojak
            
            docker network inspect indi-network >/dev/null 2>&1 || docker network create indi-network
            
            git pull origin main

            # [수정] secrets 이름을 사용자가 설정한 'APPLICATION_SECRET_YML'로 변경
            mkdir -p src/main/resources
            echo "${{ secrets.APPLICATION_SECRET_YML }}" > src/main/resources/application-secret.yml
            
            sudo docker-compose down
            sudo docker-compose up --build -d
            
            sudo docker image prune -f